version: '3.8'

services:
  api:
    build: ./src
    volumes:
      - ./src/:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    networks:
      - inv-mgmt

  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - inv-mgmt

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - inv-mgmt

networks:
  inv-mgmt:
    driver:
      bridge

volumes:
  db-data:
